{
 "title": "Gisebo",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "panels": [
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 }, "options": { "content": "## Senaste Dygnet" } },
  {
   "title": "Senaste temperatur",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_listener_v2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"gisebo-01\" or (r[\"device_id\"] == \"gisebo-05\" and r[\"_time\"] >= 2026-08-02T16:26:00Z))\n  |> filter(fn: (r) => r[\"_value\"] >= -2.0)\n  |> drop(columns: [\"device_id\", \"host\"])\r\n  |> last()\r\n  |> yield(name: \"current_temperature\")"
    }
   ]
  },
  {
   "title": "Senaste dygnet",
   "type": "timeseries",
   "description": "V5, litium + konding. I en grå låda på land med 10m kabel ut i vattnet. Termosensorn är i en Alvedon tub.",
   "gridPos": { "h": 8, "w": 17, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"home_assistant\")\r\n  |> range(start: date.sub(d: 12h, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_listener_v2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"gisebo-01\" or (r[\"device_id\"] == \"gisebo-05\" and r[\"_time\"] >= 2026-08-02T16:26:00Z))\n  |> filter(fn: (r) => r[\"_value\"] >= -2.0)\n  |> drop(columns: [\"device_id\", \"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"gisebo_01_temperature\")"
    }
   ]
  },
  {
   "title": "Lägsta temperatur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: -48h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_listener_v2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"gisebo-01\" or (r[\"device_id\"] == \"gisebo-05\" and r[\"_time\"] >= 2026-08-02T16:26:00Z))\n  |> filter(fn: (r) => r[\"_value\"] >= -2.0)\n  |> drop(columns: [\"device_id\", \"host\"])\r\n  |> min()\r\n  |> yield(name: \"lowest_temperature\")"
    }
   ]
  },
  {
   "title": "Högsta temperatur",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: -48h)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_listener_v2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"gisebo-01\" or (r[\"device_id\"] == \"gisebo-05\" and r[\"_time\"] >= 2026-08-02T16:26:00Z))\n  |> filter(fn: (r) => r[\"_value\"] >= -2.0)\n  |> drop(columns: [\"device_id\", \"host\"])\r\n  |> max()\r\n  |> yield(name: \"highest_temperature\")"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 10 }, "options": { "content": "## Senaste Veckan" } },
  {
   "title": "Senaste veckan",
   "type": "timeseries",
   "description": "V5, litium + konding. I en grå låda på land med 10m kabel ut i vattnet. Termosensorn är i en Alvedon tub.",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "import \"date\"\r\n\r\nfrom(bucket: \"home_assistant\")\r\n  |> range(start: date.sub(d: 24h, from: v.timeRangeStart), stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_listener_v2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"gisebo-01\" or (r[\"device_id\"] == \"gisebo-05\" and r[\"_time\"] >= 2026-08-02T16:26:00Z))\n  |> filter(fn: (r) => r[\"_value\"] >= -2.0)\n  |> drop(columns: [\"device_id\", \"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"gisebo_01_temperature\")"
    }
   ]
  },
  {
   "title": "Lägsta temperatur (7d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_listener_v2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"gisebo-01\" or (r[\"device_id\"] == \"gisebo-05\" and r[\"_time\"] >= 2026-08-02T16:26:00Z))\n  |> filter(fn: (r) => r[\"_value\"] >= -2.0)\n  |> drop(columns: [\"device_id\", \"host\"])\r\n  |> min()\r\n  |> yield(name: \"lowest_temperature\")"
    }
   ]
  },
  {
   "title": "Högsta temperatur (7d)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: -7d)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_listener_v2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"gisebo-01\" or (r[\"device_id\"] == \"gisebo-05\" and r[\"_time\"] >= 2026-08-02T16:26:00Z))\n  |> filter(fn: (r) => r[\"_value\"] >= -2.0)\n  |> drop(columns: [\"device_id\", \"host\"])\r\n  |> max()\r\n  |> yield(name: \"highest_temperature\")"
    }
   ]
  },
  {
   "title": "Senaste säsongen",
   "type": "timeseries",
   "description": "V5, litium + konding. I en grå låda på land med 10m kabel ut i vattnet. Termosensorn är i en Alvedon tub.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"home_assistant\")\r\n  |> range(start: 2026-06-01T00:00:00Z, stop: 2026-09-01T00:00:00Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_listener_v2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => (r[\"device_id\"] == \"gisebo-01\" and r[\"host\"] == \"61781446e5e9\") or (r[\"device_id\"] == \"gisebo-05\" and r[\"_time\"] >= 2026-08-02T16:26:00Z))\n  |> filter(fn: (r) => r[\"_value\"] >= -2.0)\n  |> drop(columns: [\"device_id\", \"host\"])\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"gisebo_01_temperature\")"
    }
   ]
  },
  {
   "title": "Året",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "data = from(bucket: \"home_assistant\")\r\n  |> range(start: 2026-01-01T00:00:00Z, stop: 2026-12-31T23:59:59Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"http_listener_v2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\r\n  |> filter(fn: (r) => r[\"device_id\"] == \"gisebo-01\" or (r[\"device_id\"] == \"gisebo-05\" and r[\"_time\"] >= 2026-08-02T16:26:00Z))\n  |> filter(fn: (r) => r[\"_value\"] >= -2.0)\r\n  |> filter(fn: (r) => r[\"host\"] != \"3027a048eee2\")\r\n  |> drop(columns: [\"host\", \"device_id\"])\r\n\r\n// Calculate each aggregation separately\r\nmin_data = data |> aggregateWindow(every: 1w, fn: min) |> set(key: \"_field\", value: \"raw_min\")\r\nmed_data = data |> aggregateWindow(every: 1w, fn: median) |> set(key: \"_field\", value: \"raw_med\")\r\nmax_data = data |> aggregateWindow(every: 1w, fn: max) |> set(key: \"_field\", value: \"raw_max\")\r\n\r\n// Align by time and calculate the stacked segments\r\naligned = union(tables: [min_data, med_data, max_data])\r\n  |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    min_seg: r.raw_min,\r\n    med_seg: r.raw_med - r.raw_min,\r\n    max_seg: r.raw_max - r.raw_med\r\n  }))\r\n\r\n// Output as three distinct time series\r\nunion(tables: [\r\n  aligned |> map(fn: (r) => ({ _time: r._time, _field: \"1_Min\", _value: r.min_seg })),\r\n  aligned |> map(fn: (r) => ({ _time: r._time, _field: \"2_Median\", _value: r.med_seg })),\r\n  aligned |> map(fn: (r) => ({ _time: r._time, _field: \"3_Max\", _value: r.max_seg }))\r\n])\r\n  |> group(columns: [\"_field\"]) // This is the crucial step to restore the timeline\r\n  |> yield(name: \"weekly_temperature_stack\")"
    }
   ]
  }
 ]
}